Updates to retry definition
serverlessworkflow/specification pull request #221
Opened 2021-01-08 00:07 UTC by jorgenj

**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ x] Specification
- [ x] Schema
- [ x] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:

Address requested changes in #137 & #136

**Special notes for reviewers**:

**Additional information (if needed):**

2021-01-08 00:46 UTC, tsurdilo requested changes

2021-01-08 00:46 UTC, tsurdilo commented on schema/retries.json
> +          "minimum": 0,
add 
"minLength": 1 
since it can also be string type

2021-01-08 00:46 UTC, tsurdilo commented on schema/retries.json
> +          "description": "Float value, if specified the delay between retries is multiplied by this value."
I would also define the decimal point precision if you require this to be a float. 
You can use "multipleOf" param when its number type.  Prob enough 1 decimal points in which case add
"multipleOf": 0.1
to multiplier

2021-01-08 00:46 UTC, tsurdilo commented on specification.md
> +| multiplier | Float value by which the delay is multiplied before each attempt. For example: "1.2" meaning that each successive delay is 20% longer than the previous delay.  For example, if delay is
Add the decimal precision info here too (1 decimal point if you define it as such with  multipleOf)

2021-01-08 00:46 UTC, tsurdilo commented on specification.md
> +after `increment`, `multiplier`, and `jitter` are applied.
no need for the last "are applied. just end sentence after 'jitter'

2021-01-08 00:46 UTC, tsurdilo commented
@jorgenj thanks for pr!

2021-01-08 00:53 UTC, tsurdilo commented
@jorgenj please also add a row to the roadmap/README.md file that points out this update. Thanks.

2021-01-11 15:28 UTC, ricardozanini reviewed
LGTM as soon as @tsurdilo's comments are taken care of.

2021-01-11 22:13 UTC, tsurdilo approved these changes

2021-01-11 22:14 UTC, tsurdilo commented
@jorgenj thanks for making the updates! It seems the DCO check is failing. Commit needs to be signed.

2021-01-11 22:33 UTC, merged