Adding title to switch
serverlessworkflow/specification pull request #905
Opened 2024-06-27 09:06 UTC by fjtirado

**Please specify parts of this PR update:**

- [ ] Specification
- [X] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Use Cases
- [ ] Community
- [ ] CTK
- [ ] Other

**Discussion or Issue link**:

**What this PR does**:

**Additional information:**

2024-06-27 09:24 UTC, cdavernas requested changes

2024-06-27 09:24 UTC, cdavernas commented on schema/workflow.yaml
> +            title: Switch
Shouldn't we call it `SwitchCase` or something of the like instead?

2024-06-27 09:25 UTC, cdavernas commented
@fjtirado Your branch is out of date 😉

2024-06-27 12:01 UTC, cdavernas approved these changes
LGTM! Thanks ❤️

2024-07-03 14:03 UTC, ricardozanini approved these changes

2024-07-04 14:11 UTC, merged