Extract datetime descriptor
serverlessworkflow/specification pull request #974
Opened 2024-08-15 09:18 UTC by matthias-pichler-warrify

Signed-off-by: Matthias Pichler <m.pichler@warrify.com>

**Please specify parts of this PR update:**

- [x] Specification
- [ ] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Use Cases
- [ ] Community
- [ ] CTK
- [ ] Other

**Discussion or Issue link**:

Closes #966

**What this PR does**:

It extracts the definition for the datetime descriptor and replaces nanosecods with seconds

**Additional information:**

2024-08-15 09:33 UTC, cdavernas requested changes
LGTM, aside from a little naming related comment.
Many thanks ❤️

2024-08-15 12:58 UTC, ricardozanini commented on dsl.md
> +| epoch.sec | `integer` | The date time as a integer value of seconds since midnight of 1970-01-01 UTC (i.e. [the Unix Epoch](https://en.wikipedia.org/wiki/Unix_time)) | `1641024000` (="2022-01-01T08
It's either `s` or `seconds`.

2024-08-15 14:23 UTC, matthias-pichler-warrify commented on dsl.md
> +| epoch.sec | `integer` | The date time as a integer value of seconds since midnight of 1970-01-01 UTC (i.e. [the Unix Epoch](https://en.wikipedia.org/wiki/Unix_time)) | `1641024000` (="2022-01-01T08
makes sense to me ... I updated the docs

2024-08-15 14:23 UTC, cdavernas approved these changes

2024-08-16 11:09 UTC, ricardozanini approved these changes

2024-08-16 14:56 UTC, merged